### ISSUE TITLE
Using Plugin as a Non-Admin Rubrik User

### ISSUE THREAD

**Issue by rfitzhugh** [rubrikinc/rubrik-plugin-for-nagios#1]
**Is your feature request related to a problem? Please describe.**

The customer would like to use this plugin with a non-admin user. Is that possible? CDM 5.0 can do API calls from an “End User”. Was the plugin designed to only use the “admin” account?

**Describe the solution you'd like**

Message from customer: 

"can you advise the correct permissions you tested for a "read only" account to be able to monitor the Rubrik system - I set up a new local user called nagios as an End User but unsure if more specific permissions required."

**Comment by Darrenswift** [comment]
Hi, is this a changeable request?

**Comment by rfitzhugh** [comment]
@Darrenswift - feel free to leave additional context or details to this request.

**Comment by railroadmanuk** [comment]
Fixed in PR https://github.com/rubrikinc/rubrik-plugin-for-nagios/pull/2, closing issue

**Comment by railroadmanuk** [comment]
We cannot use an end user role, but CDM 4.2 introduced the read only admin user, which has been tested and works. Instructions added to quick start in attached PR.
